import {
  I_TaskItem,
  E_TaskItemVisibility,
  E_TaskItemActionType,
  E_CustomAction,
} from 'features/Header/models'
import { E_Modals } from 'features/ModalManager/models'
import { E_Panels } from 'features/SidePanel/models'
import { E_Window } from 'features/WindowManager/models'
import { E_Routes } from 'models/routes'
import { E_Icon } from 'utils/helpers/icons'

export const data: I_TaskItem[] = [
  {
    name: 'sideMenu.window.characters',
    icon: E_Icon.fileUser,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.window,
    actionPayload: E_Window.characters,
  },
  {
    name: 'sideMenu.window.inventory',
    icon: E_Icon.backpack,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.window,
    actionPayload: E_Window.inventory,
  },
  {
    name: 'sideMenu.window.market',
    icon: E_Icon.store,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.window,
    actionPayload: E_Window.market,
  },
  {
    name: 'sideMenu.window.battlefield',
    icon: E_Icon.swords,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.window,
    actionPayload: E_Window.battlefield,
  },
  {
    name: 'sideMenu.window.player',
    icon: E_Icon.circlePlay,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.window,
    actionPayload: E_Window.player,
  },
  {
    name: 'sideMenu.window.textEditor',
    icon: E_Icon.fileLines,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.window,
    actionPayload: E_Window.textEditor,
  },
  {
    name: 'room-divider-0',
    icon: E_Icon.divider,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.none,
    actionPayload: null,
  },
  {
    name: 'sideMenu.roomSettings',
    icon: E_Icon.fort,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.roomSettings,
  },
  {
    name: 'sideMenu.saveGame',
    icon: E_Icon.save,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.createRoom,
  },
  {
    name: 'sideMenu.loadGames',
    icon: E_Icon.upload,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.createRoom,
  },
  {
    name: 'sideMenu.leaveRoom',
    icon: E_Icon.leaveRoom,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.none,
    actionPayload: null,
  },
  {
    name: 'room-divider-1',
    icon: E_Icon.divider,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inRoom],
    actionType: E_TaskItemActionType.none,
    actionPayload: null,
  },
  {
    name: 'sideMenu.auth',
    icon: E_Icon.login,
    visibility: [E_TaskItemVisibility.unAuthenticated],
    actionType: E_TaskItemActionType.push,
    actionPayload: E_Routes.lobby,
  },
  {
    name: 'sideMenu.returnRoom',
    icon: E_Icon.enterRoom,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inLobby],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.joinRoom,
  },
  {
    name: 'sideMenu.createRoom',
    icon: E_Icon.create,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inLobby],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.createRoom,
  },
  {
    name: 'sideMenu.joinRoom',
    icon: E_Icon.join,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inLobby],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.joinRoom,
  },
  {
    name: 'room-lobby-0',
    icon: E_Icon.divider,
    visibility: [E_TaskItemVisibility.authenticated, E_TaskItemVisibility.inLobby],
    actionType: E_TaskItemActionType.none,
    actionPayload: null,
  },
  {
    name: 'sideMenu.users',
    icon: E_Icon.users,
    visibility: [
      E_TaskItemVisibility.authenticated,
      E_TaskItemVisibility.inLobby,
      E_TaskItemVisibility.inRoom,
    ],
    actionType: E_TaskItemActionType.panel,
    actionPayload: E_Panels.users,
  },
  {
    name: 'sideMenu.chat',
    icon: E_Icon.chat,
    visibility: [
      E_TaskItemVisibility.authenticated,
      E_TaskItemVisibility.inLobby,
      E_TaskItemVisibility.inRoom,
    ],
    actionType: E_TaskItemActionType.panel,
    actionPayload: E_Panels.chat,
  },
  {
    name: 'sideMenu.settings',
    icon: E_Icon.settings,
    visibility: [
      E_TaskItemVisibility.authenticated,
      E_TaskItemVisibility.inLobby,
      E_TaskItemVisibility.inRoom,
    ],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.settings,
  },
  {
    name: 'authenticated-divider-0',
    icon: E_Icon.divider,
    visibility: [
      E_TaskItemVisibility.authenticated,
      E_TaskItemVisibility.inLobby,
      E_TaskItemVisibility.inRoom,
    ],
    actionType: E_TaskItemActionType.none,
    actionPayload: null,
  },
  {
    name: 'sideMenu.translator',
    icon: E_Icon.language,
    visibility: [E_TaskItemVisibility.all],
    actionType: E_TaskItemActionType.modal,
    actionPayload: E_Modals.translator,
  },
  {
    name: 'sideMenu.logout',
    icon: E_Icon.logout,
    visibility: [
      E_TaskItemVisibility.authenticated,
      E_TaskItemVisibility.inLobby,
      E_TaskItemVisibility.inRoom,
    ],
    actionType: E_TaskItemActionType.replace,
    actionPayload: E_CustomAction.logout,
  },
]
